output: modpacks

modpacks: # TODO: turn into list
  "example_pack": 
    <<: *modpack
    name: Example pack
    enabled: false
  'resource_test':
    <<: *modpack
  "testpack": 
    <<: *modpack
    name: base pack
    enabled: false
  
