output: modpacks
temp_path: build

modpacks: # TODO: turn into list
  "example_pack":
    <<: *modpack
    name: Example pack
  'resource_test':
    <<: *modpack
  "testpack":
    <<: *modpack
    name: base pack
    enabled: false
  
