---
output: "../../minecraft/modpackcreator/modpacks/lite_pack/src/"
mc_version: 1.10.2
optionals: true
urls: true
release_type:
- Release
- Beta
- Alpha
mods:
- Quark

#- github: copygirl/WearableBackpacks
#  tag: v1.6.0
# - direct: https://github.com/copygirl/WearableBackpacks/releases/download/v1.6.0/WearableBackpacks-1.10.2-1.6.0.jar
- Wearable Backpacks

- direct: http://asie.pl/foamfix/foamfix-0.5.4-anarchy.jar
  side: both
  feature:
    description: Anarchy Edition http://asie.pl/foamfix/
    recommendation: starred
    selected: true

- direct: http://asie.pl/foamfix/foamfix-0.5.4-law.jar
  side: client
  feature:
    description: LawFul Edition http://asie.pl/foamfix/
    recommendation: starred
    selected: false

- curse: OpenComputers

#requirements for charset
- NotEnoughCodecs
- MCMultiPart
#Charset
- direct: https://charset.asie.pl/releases/0.3.5/charset-0.3.5-audio.jar
- direct: https://charset.asie.pl/releases/0.3.5/charset-0.3.5-decoration.jar
- direct: https://charset.asie.pl/releases/0.3.5/charset-0.3.5-drama.jar
- direct: https://charset.asie.pl/releases/0.3.5/charset-0.3.5-lib.jar
- direct: https://charset.asie.pl/releases/0.3.5/charset-0.3.5-pipes.jar
- direct: https://charset.asie.pl/releases/0.3.5/charset-0.3.5-storage.jar
- direct: https://charset.asie.pl/releases/0.3.5/charset-0.3.5-tweaks.jar
- direct: https://charset.asie.pl/releases/0.3.5/charset-0.3.5-wrench.jar

- Aroma1997s Dimensional World

- Extra Utilities

#MCJty's mods
- curse: RFTools
- curse: RFTools Control
# XNet not yet released
- curse: Deep Resonance
- curse: The One Probe
  feature:
    description: Shows blocks and information
    recommendation: starred
    selected: true
- curse: Antique Atlas
- curse: Antique Atlas Overlay - Minimap

- curse: Storage Drawers

- curse: Antique Atlas
- curse: Alternate Terrain Generation

#serverside

- curse: Thump
  side: server

- curse: Thumpcord
  side: server

- curse: Morpheus
  side: server

- curse: Death Counter
  side: server

# Clientside

- curse: Neat
  side: client
  feature:
    description: shows mobs and player health
    recommendation: starred
    selected: true

- curse: Interaction Wheel
  side: client
  feature:
    description: This mod adds an interactive Interaction Wheel for context sensitive actions
    recommendation: starred
    selected: true

- curse: JourneyMap
  optional: false
  side: client
  feature:
    description: adds a minimap and allows to open your map in a browser
    #recommendation:  # | avoid
    selected: true

- curse: Mapwriter 2
  side: client
  feature:
    description: saves the map and adds a minimap
    #recommendation:  # | avoid
    selected: false true

- curse: Antique Atlas Overlay - Minimap
  side: client
  feature:
    description: displays a minimap based on the first atlas it finds in the player's inventory.
    #recommendation:  # | avoid
    selected: false

- curse: ChatFlow
  side: client

- curse: Ding
  side: client
  feature:
    description: plays a sound when minecraft finished loading
    recommendation: starred
    selected: true

# - curse: Not Enough Items 1.8.+
#   side: both #client
#   feature:
#     description: NEI
#     selected: false

- curse: Just Enough Items (JEI)
  side: both

- curse: Just Enough Resources (JER)
  side: both #client

- curse: Just Enough Buttons
  side: client

- curse: Inventory Tweaks
  side: client

- curse: Mouse Tweaks
  side: client

- curse: Schematica
  side: both
  feature:
    description: allows to save and load schemtics in the world as ghost blocks, its a great building guide
    selected: false

- curse: mineTunes
  side: client
  feature:
    description: In-game .mp3 music player complete with playlists and an interface display, cannot be loaded at the same time with Ambience (MusicMod)
    selected: false

- curse: Ambience (Music Mod)
  side: client
  feature:
    description: Environmentally aware soundtracks in Minecraft, cannot be loaded at the same time with mineTunes
    selected: true

- curse: iChunUtil
  feature:
    description: required for PiP
    selected: false

- curse: Picture-in-Picture (PiP)
  side: client
  feature:
    description: Renders other player’s Point of Views in a “Picture-in-Picture” style on the Minecraft screen when no GUI is open.
    selected: false

- direct: http://optifine.net/adloadx?f=OptiFine_1.10.2_HD_U_D6.jar
  side: client
  feature:
    name: Optifine
    description: optifine, for improving your visual quality, can create issues with other mods
    recommendation: avoid
    selected: false

- direct: http://www.karyonix.net/shadersmod/files/ShadersMod-v2.5.3mc1.10.2.jar
  side: client
  feature:
    name: shadersmod
    description: shaders make look things fancy, only install if you know what it does
    recommendation: avoid
    selected: false