---
output: "../../minecraft/modpackcreator/modpacks/magical_mayhem/src/"
mc_version: 1.10.2
optionals: true
release_type:
- Release
- Beta
- Alpha
mods:
- github: copygirl/WearableBackpacks
  tag: v1.1.0.2-beta
- jenkins:
    url: http://ci.tterrag.com/
    name: Chisel
    branch: 1.10/dev
- name: JourneyMap
  version: map-1.10.2
  release_type:
  - Release
  - Beta
- curse: Applied Energistics 2
  side: client #goes into mods/_CLIENT/
- direct: https://github.com/copygirl/BetterStorage/releases/download/v0.13.1.127/BetterStorage-1.7.10-0.13.1.127.jar
  feature:
   # https://github.com/SKCraft/Launcher/wiki/Optional-Features#via-infojson-files
    description: this is the wrong version, but Wearablebackpacks is not done yet
    recommendation: starred # | avoid
    selected: false
- 228756 #curse: project_id: 228756
- curse: Chisel # curse: name: Chisel
  side: both # goes into mods/
- direct: http://optifine.net/adloadx?f=OptiFine_1.10.2_HD_U_D2.jar
  side: client
- Extra Utilities
- VeinMiner
- RFTools
- Psi
- Baubles
- Deep Resonance
- Quark
- PSIonic Upgrades
- Totemic
- Blood Arsenal
- 'Blood Magic '
- Guide-API
- Just Enough Items (JEI)
- Actually Additions
- Correlated Potentialistics
- Roots
- Ender IO
- Refined Storage
- Botania Unofficial
- Bagginses
- Inventory Tweaks
- Hopper Ducts
- Chisels & Bits
- Progressive Automation
- Industrial Craft
- Just Enough Resources (JER)
- Super Crafting Frame
- The One Probe
